[project]
name = "elevenlabs-tts-chunker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kraigochieng", email = "kraigochieng@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=2.65.0",
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.34.0",
]

[project.scripts]
elevenlabs-tts-chunker = "elevenlabs_tts_chunker:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.vercel]
entrypoint = "src.elevenlabs_tts_chunker.main:app"